build_image:
    image: docker:git
    services:
        - docker:dind
    script:
        - sudo docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - sudo docker build -t registry.gitlab.com/kmitl-bike/kmitl-bike-django .
        - sudo docker push registry.gitlab.com/kmitl-bike/kmitl-bike-django:latest
    only:
        - master