# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='platform',
            field=models.CharField(max_length=8, verbose_name=b'Platform'),
        ),
    ]
