# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('users', models.TextField(verbose_name=b'Users')),
                ('message', models.TextField(verbose_name=b'Message')),
            ],
            options={
                'verbose_name': 'Messenger',
                'verbose_name_plural': 'Messengers',
            },
        ),
    ]
