# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 04:53
from __future__ import unicode_literals

import chat.models
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RemoveField(
            model_name='messenger',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messenger',
            name='users',
        ),
        migrations.AddField(
            model_name='messenger',
            name='message_id',
            field=models.TextField(default=-1, verbose_name=chat.models.Message),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messenger',
            name='user_id',
            field=models.TextField(default=-1, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
