# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171108_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
