# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 05:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20171108_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='payload',
            new_name='text',
        ),
    ]
