# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20171213_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='send_time',
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'datetime'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name=b'Text'),
        ),
    ]
