# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20171213_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(verbose_name=b'sender'),
        ),
    ]
