# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20171213_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, b'Read'), (2, b'Unread')], verbose_name=b'status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name=b'text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.IntegerField(choices=[(1, b'String'), (2, b'Image')], verbose_name=b'type'),
        ),
    ]
