# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20171213_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('room_name', models.TextField(verbose_name=b'room_name')),
                ('user', models.TextField(verbose_name=b'user_id')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.RemoveField(
            model_name='messenger',
            name='user_id',
        ),
        migrations.AddField(
            model_name='messenger',
            name='room_name',
            field=models.TextField(default=0, verbose_name=b'room_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messenger',
            name='message_id',
            field=models.TextField(verbose_name=b'message_id'),
        ),
    ]
