# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20171213_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.TextField(verbose_name=b'user'),
        ),
    ]
