# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20171213_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messenger',
            name='message_id',
        ),
        migrations.AddField(
            model_name='messenger',
            name='message',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chat.Message'),
            preserve_default=False,
        ),
    ]
