# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('kmitl_id', models.CharField(max_length=32, verbose_name='KMITL ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('id_card', models.CharField(max_length=255, verbose_name='ID card')),
                ('phone_no', models.CharField(max_length=32, verbose_name='Phone no.')),
                ('faculty', models.CharField(max_length=255, verbose_name='Faculty')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('forward_email', models.EmailField(max_length=254, null=True, verbose_name='Forward email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Extra Users' Profiles",
                'verbose_name': 'Extra User Profile',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('borrow_time', models.DateTimeField(auto_now_add=True, verbose_name='Borrow time')),
                ('return_time', models.DateTimeField(null=True, verbose_name='Return time')),
                ('total_time', models.CharField(max_length=16, null=True, verbose_name='Total time')),
                ('total_distance', models.CharField(max_length=16, null=True, verbose_name='Total distance')),
                ('route_line', models.TextField(default='[]', verbose_name='Route line')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.BikeUsagePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Users' Histories",
                'verbose_name': 'User History',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('gender', models.IntegerField(verbose_name='Gender')),
                ('phone_no', models.CharField(max_length=32, verbose_name='Phone no.')),
                ('point', models.IntegerField(default=100, verbose_name='Point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Users' Profiles",
                'verbose_name': 'User Profile',
            },
        ),
    ]
