# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('kmitl_id', models.CharField(blank=True, max_length=32, verbose_name=b'KMITL ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name=b'First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name=b'Last name')),
                ('id_card', models.CharField(blank=True, max_length=255, verbose_name=b'ID card')),
                ('phone_no', models.CharField(blank=True, max_length=32, verbose_name=b'Phone no.')),
                ('faculty', models.CharField(blank=True, max_length=255, verbose_name=b'Faculty')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Email')),
                ('forward_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Forward email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Extra Profile',
                'verbose_name_plural': "Users' Extra Profiles",
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('borrow_time', models.DateTimeField(auto_now_add=True, verbose_name=b'Borrow time')),
                ('return_time', models.DateTimeField(null=True, verbose_name=b'Return time')),
                ('total_time', models.CharField(max_length=16, null=True, verbose_name=b'Total time')),
                ('total_distance', models.CharField(max_length=16, null=True, verbose_name=b'Total distance')),
                ('route_line', models.TextField(default=b'[]', verbose_name=b'Route line')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Bike')),
                ('selected_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.BikeUsagePlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User History',
                'verbose_name_plural': "Users' Histories",
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('gender', models.IntegerField(choices=[(1, b'Male'), (2, b'Female'), (3, b'Other')], verbose_name=b'Gender')),
                ('phone_no', models.CharField(max_length=32, verbose_name=b'Phone no.')),
                ('point', models.IntegerField(default=100, verbose_name=b'Point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': "Users' Profiles",
            },
        ),
    ]
