# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20170428_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField(verbose_name='Point')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Initial'), (2, 'Deposit'), (3, 'Refund'), (4, 'Penalty'), (5, 'Special')], verbose_name='Transaction type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Point Transactions',
                'verbose_name': 'Point Transaction',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='point',
        ),
    ]
