# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pointtransaction_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextraprofile',
            options={'verbose_name': 'User Profile (Extra)', 'verbose_name_plural': "Users' Extra Profiles (Extra)"},
        ),
    ]
