# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170404_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraUserProfile',
            new_name='UserExtraProfile',
        ),
        migrations.AlterModelOptions(
            name='userextraprofile',
            options={'verbose_name': 'User Extra Profile', 'verbose_name_plural': "Users' Extra Profiles"},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, b'Male'), (2, b'Female'), (3, b'Other')], verbose_name=b'Gender'),
        ),
    ]
