# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name=b'Name')),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name=b'Name')),
                ('copyright', models.CharField(max_length=128, verbose_name=b'Copyright')),
                ('url', models.CharField(blank=True, max_length=128, verbose_name=b'Project URL')),
                ('license', models.CharField(blank=True, max_length=128, verbose_name=b'License')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name=b'Position name')),
                ('priority', models.PositiveIntegerField(verbose_name=b'Priority')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.AddField(
            model_name='credit',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Position'),
        ),
    ]
