# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name=b'Name')),
                ('copyright', models.CharField(max_length=128, verbose_name=b'Copyright')),
                ('url', models.CharField(blank=True, max_length=128, verbose_name=b'Project URL')),
                ('license', models.CharField(blank=True, max_length=128, verbose_name=b'License')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
