# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('platform', models.IntegerField(verbose_name='Platform')),
                ('version_code', models.CharField(max_length=32, verbose_name='Version code')),
                ('version_name', models.CharField(max_length=32, verbose_name='Version name')),
            ],
            options={
                'verbose_name_plural': 'Mobile Application Versions',
                'verbose_name': 'Mobile Application Version',
            },
        ),
        migrations.CreateModel(
            name='AndroidAppVersion',
            fields=[
                ('appversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='status.AppVersion')),
            ],
            options={
                'verbose_name_plural': 'Android Application Versions',
                'verbose_name': 'Android Application Version',
            },
            bases=('status.appversion',),
        ),
        migrations.CreateModel(
            name='IosAppVersion',
            fields=[
                ('appversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='status.AppVersion')),
            ],
            options={
                'verbose_name_plural': 'iOS Application Versions',
                'verbose_name': 'iOS Application Version',
            },
            bases=('status.appversion',),
        ),
    ]
