# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bike_name', models.CharField(max_length=64, unique=True, verbose_name='Bike name')),
                ('mac_addr', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='MAC address')),
                ('serial_no', models.CharField(max_length=32, null=True, unique=True, verbose_name='Serial no.')),
                ('barcode', models.CharField(max_length=16, null=True, unique=True, verbose_name='Barcode')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('current_lat', models.CharField(max_length=64, verbose_name='Current latitude')),
                ('current_long', models.CharField(max_length=64, verbose_name='Current longitude')),
                ('passcode', models.CharField(max_length=32, verbose_name='Passcode')),
            ],
            options={
                'verbose_name_plural': 'Bikes',
                'verbose_name': 'Bike',
            },
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255, unique=True, verbose_name='Model name')),
            ],
            options={
                'verbose_name_plural': 'Bike Models',
                'verbose_name': 'Bike Model',
            },
        ),
        migrations.CreateModel(
            name='BikeUsagePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(max_length=255, verbose_name='Plan name')),
                ('period', models.IntegerField(verbose_name='Period (minutes)')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Bike Usage Plans',
                'verbose_name': 'Bike Usage Plan',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.BikeModel'),
        ),
    ]
