# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikemodel',
            name='bike_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Bike image'),
        ),
    ]
