# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='mac_addr',
            new_name='mac_address',
        ),
    ]
