# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='available',
        ),
        migrations.AddField(
            model_name='bike',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is available'),
        ),
    ]
