# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-23 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bikestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_key',
            field=models.CharField(max_length=128, verbose_name=b'Bike key'),
        ),
    ]
