# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 09:59
from __future__ import unicode_literals

import bikes.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bikemodel_bike_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='bikemodel',
            name='bike_image',
            field=models.ImageField(blank=True, upload_to=bikes.utils.thumbnail_file_name, verbose_name='Bike image'),
        ),
    ]
