# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20170428_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeusageplan',
            name='period',
            field=models.IntegerField(verbose_name='Period (seconds)'),
        ),
    ]
