# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=64, unique=True, verbose_name=b'Day')),
                ('date', models.DateField(verbose_name=b'date')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='OperationDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=64, unique=True, verbose_name=b'Day')),
                ('open_time', models.TimeField(verbose_name=b'Open Time')),
                ('close_time', models.TimeField(verbose_name=b'Close Time')),
                ('is_operate', models.BooleanField(default=1, verbose_name=b'Is Operate')),
            ],
            options={
                'verbose_name': 'Operation Day',
                'verbose_name_plural': 'Operation Days',
            },
        ),
    ]
