# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='day',
            field=models.CharField(max_length=64, verbose_name=b'Day'),
        ),
    ]
