# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_day', '0002_auto_20180520_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationdays',
            name='is_operate',
        ),
        migrations.AddField(
            model_name='operationdays',
            name='is_operated',
            field=models.BooleanField(default=1, verbose_name=b'Is Operated'),
        ),
    ]
